exports.list = {
    "4r5e":true,
    "5h1t":true,
    "5hit":true,
    "50 yard cunt punt   ":true,
    "a2m":true,
    "a55":true,
    "a_s_s":true,
    "adult":true,
    "amateur":true,
    "anal impaler   ":true,
    "anal leakage   ":true,
    "anal":true,
    "anilingus":true,
    "anus":true,
    "ar5e":true,
    "arrse":true,
    "arse":true,
    "arsehole":true,
    "ass fuck   ":true,
    "ass":true,
    "ass-fucker":true,
    "asses":true,
    "assfucker":true,
    "assfukka":true,
    "asshole":true,
    "assholes":true,
    "assmucus   ":true,
    "assmunch":true,
    "asswhole":true,
    "autoerotic":true,
    "b00bs":true,
    "b1tch":true,
    "b17ch":true,
    "b!tch":true,
    "ballbag":true,
    "balls":true,
    "ballsack":true,
    "bangbros":true,
    "bareback":true,
    "bastard":true,
    "beastial":true,
    "beastiality":true,
    "beef curtain   ":true,
    "bellend":true,
    "bestial":true,
    "bestiality":true,
    "bi+ch":true,
    "biatch":true,
    "bimbos":true,
    "birdlock":true,
    "bitch tit   ":true,
    "bitch":true,
    "bitcher":true,
    "bitchers":true,
    "bitches":true,
    "bitchin":true,
    "bitching":true,
    "bloody":true,
    "blow job":true,
    "blow me   ":true,
    "blow mud   ":true,
    "blowjob":true,
    "blowjobs":true,
    "blue waffle   ":true,
    "blumpkin   ":true,
    "boiolas":true,
    "bollock":true,
    "bollok":true,
    "boner":true,
    "boob":true,
    "boobs":true,
    "booobs":true,
    "boooobs":true,
    "booooobs":true,
    "booooooobs":true,
    "breasts":true,
    "buceta":true,
    "bugger":true,
    "bum":true,
    "bunny fucker":true,
    "bust a load   ":true,
    "busty":true,
    "butt fuck   ":true,
    "butt":true,
    "butthole":true,
    "buttmuch":true,
    "buttplug":true,
    "c0ck":true,
    "c0cksucker":true,
    "carpet muncher":true,
    "carpetmuncher":true,
    "cawk":true,
    "chink":true,
    "choade   ":true,
    "chota bags   ":true,
    "cipa":true,
    "cl1t":true,
    "clit licker   ":true,
    "clit":true,
    "clitoris":true,
    "clits":true,
    "clitty litter   ":true,
    "clusterfuck":true,
    "cnut":true,
    "cock pocket   ":true,
    "cock snot   ":true,
    "cock":true,
    "cock-sucker":true,
    "cockface":true,
    "cockhead":true,
    "cockmunch":true,
    "cockmuncher":true,
    "cocks":true,
    "cocksuck ":true,
    "cocksucked ":true,
    "cocksucker":true,
    "cocksucking":true,
    "cocksucks ":true,
    "cocksuka":true,
    "cocksukka":true,
    "cok":true,
    "cokmuncher":true,
    "coksucka":true,
    "coon":true,
    "cop some wood   ":true,
    "cornhole   ":true,
    "corp whore   ":true,
    "cox":true,
    "crap":true,
    "cum chugger   ":true,
    "cum dumpster   ":true,
    "cum freak   ":true,
    "cum guzzler   ":true,
    "cum":true,
    "cumdump   ":true,
    "cummer":true,
    "cumming":true,
    "cums":true,
    "cumshot":true,
    "cunilingus":true,
    "cunillingus":true,
    "cunnilingus":true,
    "cunt hair   ":true,
    "cunt":true,
    "cunt-struck   ":true,
    "cuntbag   ":true,
    "cuntlick ":true,
    "cuntlicker ":true,
    "cuntlicking ":true,
    "cunts":true,
    "cuntsicle   ":true,
    "cut rope   ":true,
    "cyalis":true,
    "cyberfuc":true,
    "cyberfuck ":true,
    "cyberfucked ":true,
    "cyberfucker":true,
    "cyberfuckers":true,
    "cyberfucking ":true,
    "d1ck":true,
    "damn":true,
    "dick hole   ":true,
    "dick shy   ":true,
    "dick":true,
    "dickhead":true,
    "dildo":true,
    "dildos":true,
    "dink":true,
    "dinks":true,
    "dirsa":true,
    "dirty Sanchez   ":true,
    "dlck":true,
    "dog-fucker":true,
    "doggie style":true,
    "doggiestyle":true,
    "doggin":true,
    "dogging":true,
    "donkeyribber":true,
    "doosh":true,
    "duche":true,
    "dyke":true,
    "eat a dick   ":true,
    "eat hair pie   ":true,
    "ejaculate":true,
    "ejaculated":true,
    "ejaculates ":true,
    "ejaculating ":true,
    "ejaculatings":true,
    "ejaculation":true,
    "ejakulate":true,
    "erotic":true,
    "f4nny":true,
    "f u c k e r":true,
    "f u c k":true,
    "f_u_c_k":true,
    "facial   ":true,
    "fag":true,
    "fagging":true,
    "faggitt":true,
    "faggot":true,
    "faggs":true,
    "fagot":true,
    "fagots":true,
    "fags":true,
    "fanny":true,
    "fannyflaps":true,
    "fannyfucker":true,
    "fanyy":true,
    "fatass":true,
    "fcuk":true,
    "fcuker":true,
    "fcuking":true,
    "feck":true,
    "fecker":true,
    "felching":true,
    "fellate":true,
    "fellatio":true,
    "fingerfuck ":true,
    "fingerfucked ":true,
    "fingerfucker ":true,
    "fingerfuckers":true,
    "fingerfucking ":true,
    "fingerfucks ":true,
    "fist fuck   ":true,
    "fistfuck":true,
    "fistfucked ":true,
    "fistfucker ":true,
    "fistfuckers ":true,
    "fistfucking ":true,
    "fistfuckings ":true,
    "fistfucks ":true,
    "flange":true,
    "flog the log   ":true,
    "fook":true,
    "fooker":true,
    "fuck hole   ":true,
    "fuck puppet   ":true,
    "fuck trophy   ":true,
    "fuck yo mama   ":true,
    "fuck":true,
    "fuck-ass   ":true,
    "fuck-bitch   ":true,
    "fucka":true,
    "fucked":true,
    "fucker":true,
    "fuckers":true,
    "fuckhead":true,
    "fuckheads":true,
    "fuckin":true,
    "fucking":true,
    "fuckings":true,
    "fuckingshitmotherfucker":true,
    "fuckme ":true,
    "fuckmeat   ":true,
    "fucks":true,
    "fucktoy   ":true,
    "fuckwhit":true,
    "fuckwit":true,
    "fuck   ":true,
    "fudge packer":true,
    "fudgepacker":true,
    "fuk":true,
    "fuker":true,
    "fukker":true,
    "fukkin":true,
    "fuks":true,
    "fukwhit":true,
    "fukwit":true,
    "fux0r":true,
    "fux":true,
    "gang-bang   ":true,
    "gangbang":true,
    "gangbanged ":true,
    "gangbangs ":true,
    "gangbang   ":true,
    "gassy ass   ":true,
    "gaylord":true,
    "gaysex":true,
    "goatse":true,
    "God damn":true,
    "god":true,
    "god-dam":true,
    "god-damned":true,
    "Goddamn":true,
    "goddamned":true,
    "ham flap   ":true,
    "hardcoresex ":true,
    "hell":true,
    "heshe":true,
    "hoar":true,
    "hoare":true,
    "hoer":true,
    "homo":true,
    "homoerotic":true,
    "hore":true,
    "horniest":true,
    "horny":true,
    "hotsex":true,
    "how to kill":true,
    "how to murdep":true,
    "jack-off ":true,
    "jackoff":true,
    "jap":true,
    "jerk":true,
    "jerk-off ":true,
    "jism":true,
    "jiz ":true,
    "jizm ":true,
    "jizz":true,
    "kawk":true,
    "kinky Jesus   ":true,
    "knob end":true,
    "knob":true,
    "knobead":true,
    "knobed":true,
    "knobend":true,
    "knobhead":true,
    "knobjocky":true,
    "knobjokey":true,
    "kock":true,
    "kondum":true,
    "kondums":true,
    "kum":true,
    "kummer":true,
    "kumming":true,
    "kums":true,
    "kunilingus":true,
    "kwif   ":true,
    "l3i+ch":true,
    "l3itch":true,
    "labia":true,
    "LEN":true,
    "lmao":true,
    "lmfao":true,
    "lust":true,
    "lusting":true,
    "m0f0":true,
    "m0fo":true,
    "m45terbate":true,
    "ma5terb8":true,
    "ma5terbate":true,
    "mafugly   ":true,
    "masochist":true,
    "master-bate":true,
    "masterb8":true,
    "masterbat3":true,
    "masterbat*":true,
    "masterbate":true,
    "masterbation":true,
    "masterbations":true,
    "masturbate":true,
    "mo-fo":true,
    "mof0":true,
    "mofo":true,
    "mothafuck":true,
    "mothafucka":true,
    "mothafuckas":true,
    "mothafuckaz":true,
    "mothafucked ":true,
    "mothafucker":true,
    "mothafuckers":true,
    "mothafuckin":true,
    "mothafucking ":true,
    "mothafuckings":true,
    "mothafucks":true,
    "mother fucker":true,
    "mother fucker   ":true,
    "motherfuck":true,
    "motherfucked":true,
    "motherfucker":true,
    "motherfuckers":true,
    "motherfuckin":true,
    "motherfucking":true,
    "motherfuckings":true,
    "motherfuckka":true,
    "motherfucks":true,
    "muff puff   ":true,
    "muff":true,
    "mutha":true,
    "muthafecker":true,
    "muthafuckker":true,
    "muther":true,
    "mutherfucker":true,
    "n1gg3r":true,
    "n1gg4":true,
    "n1gga":true,
    "n1gger":true,
    "nazi":true,
    "need the dick   ":true,
    "nigg3r":true,
    "nigg4h":true,
    "nigga":true,
    "niggah":true,
    "niggas":true,
    "niggaz":true,
    "nigger":true,
    "niggers ":true,
    "nob jokey":true,
    "nob":true,
    "nobhead":true,
    "nobjocky":true,
    "nobjokey":true,
    "numbnuts":true,
    "nut butter   ":true,
    "nutsack":true,
    "omg":true,
    "orgasim ":true,
    "orgasims ":true,
    "orgasm":true,
    "orgasms ":true,
    "p0rn":true,
    "pawn":true,
    "pecker":true,
    "penis":true,
    "penisfucker":true,
    "phonesex":true,
    "phuck":true,
    "phuk":true,
    "phuked":true,
    "phuking":true,
    "phukked":true,
    "phukking":true,
    "phuks":true,
    "phuq":true,
    "pigfucker":true,
    "pimpis":true,
    "piss":true,
    "pissed":true,
    "pisser":true,
    "pissers":true,
    "pisses ":true,
    "pissflaps":true,
    "pissin ":true,
    "pissing":true,
    "pissoff ":true,
    "poop":true,
    "porn":true,
    "porno":true,
    "pornography":true,
    "pornos":true,
    "prick":true,
    "pricks ":true,
    "pron":true,
    "pube":true,
    "pusse":true,
    "pussi":true,
    "pussies":true,
    "pussy fart   ":true,
    "pussy palace   ":true,
    "pussy":true,
    "pussys ":true,
    "queaf   ":true,
    "queer":true,
    "rectum":true,
    "retard":true,
    "rimjaw":true,
    "rimming":true,
    "s hit":true,
    "s.o.b.":true,
    "s_h_i_t":true,
    "sadism":true,
    "sadist":true,
    "sandbar   ":true,
    "sausage queen   ":true,
    "schlong":true,
    "screwing":true,
    "scroat":true,
    "scrote":true,
    "scrotum":true,
    "semen":true,
    "sex":true,
    "sh1t":true,
    "sh!+":true,
    "sh!t":true,
    "shag":true,
    "shagger":true,
    "shaggin":true,
    "shagging":true,
    "shemale":true,
    "shi+":true,
    "shit fucker   ":true,
    "shit":true,
    "shitdick":true,
    "shite":true,
    "shited":true,
    "shitey":true,
    "shitfuck":true,
    "shitfull":true,
    "shithead":true,
    "shiting":true,
    "shitings":true,
    "shits":true,
    "shitted":true,
    "shitter":true,
    "shitters ":true,
    "shitting":true,
    "shittings":true,
    "shitty ":true,
    "skank":true,
    "slope   ":true,
    "slut bucket   ":true,
    "slut":true,
    "sluts":true,
    "smegma":true,
    "smut":true,
    "snatch":true,
    "soapbox":true,
    "son-of-a-bitch":true,
    "spac":true,
    "spunk":true,
    "t1tt1e5":true,
    "t1tties":true,
    "teets":true,
    "teez":true,
    "testical":true,
    "testicle":true,
    "tit wank   ":true,
    "tit":true,
    "titfuck":true,
    "tits":true,
    "titt":true,
    "tittie5":true,
    "tittiefucker":true,
    "titties":true,
    "tittyfuck":true,
    "tittywank":true,
    "titwank":true,
    "tosser":true,
    "tuanha":true,
    "turd":true,
    "tw4t":true,
    "twat":true,
    "twathead":true,
    "twatty":true,
    "twunt":true,
    "twunter":true,
    "v1gra":true,
    "v14gra":true,
    "vagina":true,
    "viagra":true,
    "vulva":true,
    "w00se":true,
    "wang":true,
    "wank":true,
    "wanker":true,
    "wanky":true,
    "whoar":true,
    "whore":true,
    "willies":true,
    "willy":true,
    "winifix":true,
    "wtf":true,
    "xrated":true,
    "xxx":true,
}
